#pragma once

/**
 * @brief Events generated by ESP32 (sent to Central/Controller)
 */
typedef enum {
    COMMS_EVENT_END,
    COMMS_EVENT_STOPPED,
    COMMS_EVENT_SHOOT
} comms_event_t;

/**
 * @brief Commands received from Central/Controller
 */
typedef enum {
    COMMS_CMD_START,
    COMMS_CMD_STOP,
    COMMS_CMD_NEXT,
    COMMS_CMD_RESUME
} comms_cmd_t;

/**
 * @brief Callback type for receiving commands from Central/Controller
 */
typedef void (*comms_cmd_event_handler_t)(comms_cmd_t cmd);
