#pragma once

#include <stdint.h>
#include "esp_err.h"

/**
 * @brief Initialize the BLE stack and GATT server for comms
 * @note Initialize nvs_flash before calling this function
 * This function sets up the BLE stack, registers the comms service and 
 * characteristics, and stores the callback for incoming commands.
 *
 * @param callback Function pointer called when a command is received from Central
 * @return ESP_OK on success, error code otherwise
 */
esp_err_t comms_init(comms_cmd_event_handler_t event_handler);

/**
 * @brief Start BLE advertising so a Central/Controller can connect
 *
 * @return ESP_OK on success, error code otherwise
 */
esp_err_t comms_start_advertising(void);

/**
 * @brief Send an event to the connected Central/Controller
 *
 * This notifies the Central about an event generated by the ESP32.
 *
 * @param event Event enum to send
 * @return ESP_OK on success, error code otherwise
 */
esp_err_t comms_send_event(comms_event_t event);

